name: Package Application with Pyinstaller

on:
  push:
    branches: [ master, pipeline ]
  pull_request:
    branches: [ master ]

jobs:
  build_win:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: nasalib2bibtex-Portable-win-x64
        path: dist/windows
        
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: nasalib2bibtex-Portable-linux-x64
        path: dist/linux
